services:
  nats-a:
    image: nats:latest
    command: [ "-c", "/etc/nats/nats-server.conf" ]
    volumes:
      - ./nats-a.conf:/etc/nats/nats-server.conf
    ports:
      - "4222:4222"
      - "6222:6222"
  nats-b:
    image: nats:latest
    command: [ "-c", "/etc/nats/nats-server.conf" ]
    volumes:
      - ./nats-b.conf:/etc/nats/nats-server.conf
    ports:
      - "5222:4222"
      - "7222:6222"
